### ISSUE TITLE
Error: Default GPU_MEM_LIMIT in mask_ops.py is too small

### ISSUE THREAD

**Issue by WeiweiDuan** [DARPA-CRITICALMAAS/uncharted-ta1#1]
I ran the segmentation pipeline on the Hackathon 2 test maps. Some maps (e.g., 67434_112084.tif) got the following error: 
EXCEPTION executing pipeline at step 0 for raster 67434_112084
Default GPU_MEM_LIMIT in mask_ops.py is too small; try increasing it

Is there any solution to this error? Thanks for your help.

**Comment by dgiesbrecht** [comment]
Hi. Yes, we have seen this issue occasionally - due to the internal Detectron2 lib configuration. We will try to commit a work-around. In the meantime, you could try running the model on CPU for those images. The model usually runs in 1-2 sec per map on CPU.

**Comment by dgiesbrecht** [comment]
A fix for this has just been merged.
(Detectron mem threshold was increased)

**Comment by WeiweiDuan** [comment]
Thanks. I'll pull the updated repo.
